source 'https://rubygems.org'

ruby '2.4.5'

gem 'rails', '4.2.8'

# Stores the todo list.
gem 'sqlite3', '~> 1.3.6'

# Templating library for views.
gem 'haml'

# The actual web server.
gem 'thin'

# Rack middleware authentication framework.
gem 'omniauth'

# AzureAD specific strategy for OmniAuth.
gem 'omniauth-azure-activedirectory'

# Loads configurations from .env into ENV hash.
gem 'dotenv'

# Acquires access tokens for resources.
gem 'adal', git: 'https://github.com/AzureAD/azure-activedirectory-library-for-ruby.git'

# For the front end.
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'turbolinks'

# Debugging
gem 'byebug'
